version: "3"

services:
  lava-server:
    #image: lavasoftware/lava-server:2019.01
    image: lava-server
    container_name: lava-server
    ports:
      - "8080:80"
    volumes:
    - /opt/postgresql:/var/lib/postgresql
    - /opt/lava-server:/var/lib/lava-server
    privileged: true
    hostname: lava-server
    networks:
      - lava-net

  lava-dispatcher:
    #image: lavasoftware/lava-dispatcher:2019.01
    image: lava-dispatcher
    container_name: lava-dispatcher
    #privileged: true
    hostname: lava-dispatcher
    volumes:
      - /opt/dispatcher:/var/lib/lava/dispatcher/tmp
    environment:
      - DISPATCHER_HOSTNAME=--hostname=dispatcher01
      - LOGGER_URL=tcp://lava-server:5555
      - MASTER_URL=tcp://lava-server:5556
    networks:
      - lava-net
       
networks:
  lava-net:

